data "azurerm_key_vault" "key_vault" {
  count               = local.require_key_vault
  name                = var.update_key_vault.keyvault_name
  resource_group_name = var.update_key_vault.resource_group_name
}

resource "azurerm_key_vault_secret" "aad_appclient_id" {
  count        = local.require_key_vault
  key_vault_id = one(data.azurerm_key_vault.key_vault[*]).id
  name         = local.kv_client_id_name
  value        = azuread_application.application.client_id
  content_type = "Generated by Terraform"
}


resource "azurerm_key_vault_secret" "client_secret" {
  count           = local.require_key_vault
  key_vault_id    = one(data.azurerm_key_vault.key_vault[*]).id
  name            = local.kv_client_secret_name
  value           = tolist(azuread_application.application.password).0.value
  expiration_date = time_rotating.rotate365[0].rotation_rfc3339
  content_type    = "Generated by Terraform <-> Run terraform apply to rotate the secret"
}
